### ISSUE TITLE
make error: ‘_Ref_count_obj’ is not a class template

### ISSUE THREAD

**Issue by jasonkhanlar** [Xaymar/obs-stream-effects#60]
**Describe the bug**
Working with v0.5.0 source code: https://github.com/Xaymar/obs-stream-effects/archive/0.5.0.tar.gz in an Archlinux environment:

cmake: https://pastebin.com/raw/xAdbjYrh
make: https://pastebin.com/raw/SwRUYvaA
```
obs-stream-effects-0.5.0/source/obs/obs-source-tracker.hpp:37:21: error: ‘_Ref_count_obj’ is not a class template
   friend class std::_Ref_count_obj<obs::source_tracker>;
```

**To Reproduce**
1. cmake
2. make

**Expected behavior**
Source code should compile in a GNU/Linux environment

**Desktop (please complete the following information):**
 - Operating System: Linux
 - Kernel Version: 4.19.34

**Comment by Xaymar** [comment]
See #31.

**Comment by Xaymar** [comment]
There's a lot of work required to make the code compatible with linux building, especially with gcc. I have recently begun making it compatible with clang (not vs-clang-cl), which should bring it closer to the actual c++ standard that is portable.

**Comment by jasonkhanlar** [comment]
Alright. I'm working on preparing an Archlinux AUR package to install this and publish at https://aur.archlinux.org/packages/ All that is needed for it to work in Linux is a *.so file (instead of *.dll).

**Comment by Xaymar** [comment]
Oh by the way, currently I don't actually know if it can link to obs correctly, as it downloads the windows obs-studio package. I don't know how to make Travis upload linux packages, so I might have to also move that to AppVeyor.

**Comment by Xaymar** [comment]
Should now be fixed.
